import { Noto_Sans_KR } from "next/font/google";

import { Navbar } from "./components/layout/Nav";
import { Footer } from "./components/layout/Footer";

import "./globals.css";
import "./components/gyoon-dark-code-block.css";

// KaTeX CSS 추가
import "katex/dist/katex.min.css";

const notoSansKR = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Inticoy's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`bg-white dark:bg-inticoy-dark ${notoSansKR.variable} antialiased`}
      >
        <Navbar />
        <div
          className="
            w-full h-48 p-8 top-0 z-20 
            flex flex-row items-center 
            bg-[url('/img/index.jpg')] 
            bg-cover bg-center"
        />
        <div
          className="
              w-full
              md:max-w-4xl px-6 md:px-8 mb-16 m-auto 
              break-words
              text-black dark:text-white
              prose prose:invert"
        >
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
